[project]
name = "regia"
version = "0.2.0"
description = "A Domain Specific Language for Game Designers to model Agent behaviour and Game flow, compiled to AgentSpeak."
requires-python = ">=3.11"

dependencies = [
  "click>=8.1,<9",  # cli
  "fastapi",  # web server
  "lark>=1.2,<2",  # parser
  "pydantic",  # validation
  "uvicorn",  # web server runner
]

[project.scripts]
regia = "regia.cli:main"

# == Development dependencies ==================================================
[project.optional-dependencies]
dev = [
  "pytest>=8.0",
  "syrupy>=4.0",
]
benchmarks = [
  "pandas",
  "matplotlib",
]

# == Build system ==============================================================
[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

# == Pytest configuration ======================================================
[tool.pytest.ini_options]
testpaths = ["automated_tests"]

[tool.setuptools.packages.find]
where = ["src"]

# Include the .lark grammar file in the package
[tool.setuptools.package-data]
regia = ["grammars/*.lark"]
