// ============================================
// Director agent for Plot: RoyalBanquet
// ============================================
// Generated by the Regia v0.2 compiler
//
// desc: The main narrative flow of the Royal Banquet.


// ============================================
// == Initial Beliefs ==
// ============================================
plot_name(royalbanquet).
current_phase(reception).

// ============================================
// == Boot Plan ==
// ============================================
// Runs when the Director agent is created.
// Registers plot identity and executes ON ENTER for the initial phase.
@boot__RoyalBanquet[atomic]
+!boot <-
    .my_name(Me);
    +plot_id(Me);
    .print("[RoyalBanquet] Booting up director agent ", Me, " in phase 'reception'...");
    !on_enter(reception).

// == Director WHEN Plans ==
@dir__RoyalBanquet__assassin_spotted__0[priority(9)]
+assassin_spotted : true <-
    lock_doors;
    !send_to_role(host, achieve, call_guards);
    !end_plot.

@dir__RoyalBanquet__food_served__0
+food_served : current_phase(reception) <-
    !switch_phase(feast).

@dir__RoyalBanquet__guest_signals_insult_thrown__0
+insult_thrown[source(Sender)] : current_phase(feast) & role_agent(guest, Sender) <-
    stop_music;
    !start_subplot("honorduel", honorduel, [map(challenger, guest)]);
    !switch_phase(duel_interruption).

@dir__RoyalBanquet__subplot_honorduel_ended__0
+!subplot_ended(honorduel) : current_phase(duel_interruption) <-
    .print("The duel is settled. The banquet is ruined.");
    !end_plot.


// ============================================
// == Phase Transition Infrastructure ==
// ============================================
@switch_phase_atomic[atomic]
+!switch_phase(Target) : current_phase(Current) <-
    .print("[RoyalBanquet] Transitioning from phase '", Current, "' to '", Target, "'...");
    !on_exit(Current);
    -current_phase(Current);
    +current_phase(Target);
    !on_enter(Target).

+!on_enter(reception) <-
    play_music;
    !send_to_role(guest, achieve, add_playbook(noblesocializing)).
+!on_exit(feast) <-
    !send_to_role(guest, achieve, remove_playbook(noblesocializing)).
+!on_enter(feast) <-
    serve_wine.
+!on_exit(_) <- true.
+!on_enter(_) <- true.

// ============================================
// == Plot Lifecycle Infrastructure ==
// ============================================
// If the parent terminates, it signals children with !parent_ended
+!parent_ended[source(Parent)] : parent_plot(Parent) <-
    .print("[RoyalBanquet] Parent plot ", Parent, " ended. Terminating this subplot...");
    -parent_plot(Parent);
    !end_plot.

@end_plot_atomic[atomic]
+!end_plot : current_phase(Current) <-
    .my_name(Me);
    .print("[RoyalBanquet] Ending plot. Running exit hooks and broadcasting termination...");
    !on_exit(Current);
    .findall(C, child_plot(C, _, _), Children);
    for ( .member(Child, Children) ) { .send(Child, achieve, parent_ended) };
    .findall(A, role_agent(_, A), Roles);
    for ( .member(RoleAgent, Roles) ) { .send(RoleAgent, achieve, plot_ended(Me)) };
    !notify_parent;
    .kill_agent(Me).

+!notify_parent : parent_plot(Parent) <-
    .my_name(Me);
    .send(Parent, achieve, child_ended(royalbanquet, Me)).
+!notify_parent <- true.

// Infrastructural cleanup when a child plot ends
@dir__infrastructure__child_ended[atomic]
+!child_ended(SubplotName, ChildId) <-
    .term2string(ChildId, ChildIdStr);
    .print("[RoyalBanquet] Subplot ", SubplotName, " (", ChildIdStr, ") ended. Cleaning up registry...");
    -child_plot(ChildIdStr, SubplotName, _);
    !!subplot_ended(SubplotName).

// Fallback to prevent Jason warnings if the user didn't write a WHEN SUBPLOT ENDS block
+!subplot_ended(_) <- true.

@start_subplot_atomic[atomic]
+!start_subplot(SubplotStr, SubplotAtom, MappingsData) <-
    !build_bindings(MappingsData, Bindings);
    // uses current time to generate new distinct sub-plot agent id
    .time(HH, MM, SS, MS);
    .my_name(Me);
    .concat(SubplotStr, "_", Me, "_", MS, ChildId);
    .concat("director_", SubplotStr, ".asl", SourceFile);
    .print("[RoyalBanquet] Spawning subplot '", SubplotStr, "' as agent ", ChildId, " with bindings ", Bindings);
    .create_agent(ChildId, SourceFile);
    .send(ChildId, achieve, start_plot(Bindings));
    .send(ChildId, tell, parent_plot(Me));
    +child_plot(ChildId, SubplotAtom, MappingsData).

// Recursive helper to build role agent bindings from mappings
+!build_bindings([], []).
+!build_bindings([map(Target, Source) | RestMappings], [map(Target, Agents) | RestBindings]) <-
    .findall(A, role_agent(Source, A), Agents);
    !build_bindings(RestMappings, RestBindings).

// ============================================
// == Role-Agent Registry ==
// ============================================
// Populated at plot startup via !start_plot.
@dir__RoyalBanquet__start_plot__0
+!start_plot(Bindings) <-
    for ( .member(map(Role, Agents), Bindings) ) {
        for ( .member(Agent, Agents) ) {
            +role_agent(Role, Agent);
        }
    };
    !boot.

@dir__RoyalBanquet__send_to_role__0
+!send_to_role(Role, Performative, Content) <-
    .findall(A, role_agent(Role, A), Agents);
    .send(Agents, Performative, Content).

// Handle agent death (broadcast by the environment) to avoid stalling
@dir__RoyalBanquet__agent_died__0[atomic]
+agent_died(DeadAgent) : role_agent(Role, DeadAgent) <-
    .print("[RoyalBanquet] Agent ", DeadAgent, " playing role '", Role, "' has died! Cleaning registry...");
    -role_agent(Role, DeadAgent).

