// ============================================
// Director agent for Plot: SubTask
// ============================================
// Generated by the Regia v0.2 compiler

// ============================================
// == Initial Beliefs ==
// ============================================
plot_name(subtask).
current_phase(working).

// ============================================
// == Boot Plan ==
// ============================================
// Runs when the Director agent is created.
// Registers plot identity and executes ON ENTER for the initial phase.
@boot__SubTask[atomic]
+!boot <-
    .my_name(Me);
    +plot_id(Me);
    .print("[SubTask] Booting up director agent ", Me, " in phase 'working'...");
    !on_enter(working).

// == Director WHEN Plans ==
@dir__SubTask__task_finished__0
+task_finished : current_phase(working) <-
    .print("SubTask completed!");
    !end_plot.


// ============================================
// == Phase Transition Infrastructure ==
// ============================================
@switch_phase_atomic[atomic]
+!switch_phase(Target) : current_phase(Current) <-
    .print("[SubTask] Transitioning from phase '", Current, "' to '", Target, "'...");
    !on_exit(Current);
    -current_phase(Current);
    +current_phase(Target);
    !on_enter(Target).

+!on_enter(working) <-
    !send_to_role(assignee, tell, add_playbook(Specialist)).
+!on_exit(_) <- true.
+!on_enter(_) <- true.

// ============================================
// == Plot Lifecycle Infrastructure ==
// ============================================
@end_plot_atomic[atomic]
+!end_plot : current_phase(Current) <-
    .print("[SubTask] Ending plot. Running exit hooks and broadcasting termination...");
    !on_exit(Current);
    .findall(C, child_plot(C, _, _), Children);
    for ( .member(Child, Children) ) { .send(Child, tell, parent_ended) };
    .findall(A, role_agent(_, A), Roles);
    for ( .member(RoleAgent, Roles) ) { .send(RoleAgent, tell, plot_ended(Me)) };
    !notify_parent;
    .kill_agent(Me).

+!notify_parent : parent_plot(Parent) <-
    .send(Parent, tell, child_ended(subtask, Me)).
+!notify_parent <- true.

@start_subplot_atomic[atomic]
+!start_subplot(SubplotStr, SubplotAtom, MappingsData) <-
    !build_bindings(MappingsData, Bindings);
    // uses current time to generate new distinct sub-plot agent id
    .time(HH, MM, SS, MS);
    .concat(SubplotStr, "_", plot_id(Me), "_", MS, ChildId);
    .concat("director_", SubplotStr, ".asl", SourceFile);
    .print("[SubTask] Spawning subplot '", SubplotStr, "' as agent ", ChildId, " with bindings ", Bindings);
    .create_agent(ChildId, SourceFile);
    .send(ChildId, achieve, start_plot(Bindings));
    .send(ChildId, tell, parent_plot(Me));
    +child_plot(ChildId, SubplotAtom, MappingsData).

// Recursive helper to build role agent bindings from mappings
+!build_bindings([], []).
+!build_bindings([map(Target, Source) | RestMappings], [map(Target, Agents) | RestBindings]) <-
    .findall(A, role_agent(Source, A), Agents);
    !build_bindings(RestMappings, RestBindings).

// ============================================
// == Role-Agent Registry ==
// ============================================
// Populated at plot startup via !start_plot.
@dir__SubTask__start_plot__0
+!start_plot(Bindings) <-
    for ( .member(role_agent(Role, Agent), Bindings) ) {
        +role_agent(Role, Agent);
    }.

@dir__SubTask__send_to_role__0
+!send_to_role(Role, Performative, Content) <-
    .findall(A, role_agent(Role, A), Agents);
    .send(Agents, Performative, Content).

// Handle agent death (broadcast by the environment) to avoid stalling
@dir__SubTask__agent_died__0[atomic]
+agent_died(DeadAgent) : role_agent(Role, DeadAgent) <-
    .print("[SubTask] Agent ", DeadAgent, " playing role '", Role, "' has died! Cleaning registry...");
    -role_agent(Role, DeadAgent).

