// ============================================
// Director agent for Plot: EpicAdventure
// ============================================
// Generated by the Regia v0.2 compiler

// ============================================
// == Initial Beliefs ==
// ============================================
plot_name(epicadventure).
current_phase(beginning).

// ============================================
// == Boot Plan ==
// ============================================
// Runs when the Director agent is created.
// Registers plot identity and executes ON ENTER for the initial phase.
@boot__EpicAdventure[atomic]
+!boot <-
    .my_name(Me);
    +plot_id(Me);
    .print("[EpicAdventure] Booting up director agent ", Me, " in phase 'beginning'...");
    !on_enter(beginning).

// == Director WHEN Plans ==
@dir__EpicAdventure__quest_completed__0
+quest_completed : current_phase(beginning) <-
    !switch_phase(middle).

@dir__EpicAdventure__quest_completed__0[priority(10)]
+quest_completed : current_phase(beginning) & not (has_achievement(hero_medal)) <-
    .broadcast(tell, "Giving hero a medal!");
    !switch_phase(middle).

@dir__EpicAdventure__quest_completed__1[priority(10)]
+quest_completed : current_phase(beginning) & not (not (has_achievement(hero_medal))) <-
    .broadcast(tell, "Hero already has the medal.");
    !switch_phase(ending).

@dir__EpicAdventure__quest_completed__0
+quest_completed : current_phase(middle) <-
    .broadcast(tell, "Quest completed again!");
    !switch_phase(ending).


// ============================================
// == Phase Transition Infrastructure ==
// ============================================
@switch_phase_atomic[atomic]
+!switch_phase(Target) : current_phase(Current) <-
    .print("[EpicAdventure] Transitioning from phase '", Current, "' to '", Target, "'...");
    !on_exit(Current);
    -current_phase(Current);
    +current_phase(Target);
    !on_enter(Target).

+!on_enter(middle) <-
    !send_to_role(hero, achieve, add_playbook(heroplaybook)).
+!on_enter(ending) <-
    !send_to_role(hero, achieve, remove_playbook(heroplaybook)).
+!on_exit(_) <- true.
+!on_enter(_) <- true.

// ============================================
// == Plot Lifecycle Infrastructure ==
// ============================================
// If the parent terminates, it signals children with !parent_ended
+!parent_ended[source(Parent)] : parent_plot(Parent) <-
    .print("[EpicAdventure] Parent plot ", Parent, " ended. Terminating this subplot...");
    -parent_plot(Parent);
    !end_plot.

@end_plot_atomic[atomic]
+!end_plot : current_phase(Current) <-
    .my_name(Me);
    .print("[EpicAdventure] Ending plot. Running exit hooks and broadcasting termination...");
    !on_exit(Current);
    .findall(C, child_plot(C, _, _), Children);
    for ( .member(Child, Children) ) { .send(Child, achieve, parent_ended) };
    .findall(A, role_agent(_, A), Roles);
    for ( .member(RoleAgent, Roles) ) { .send(RoleAgent, achieve, plot_ended(Me)) };
    !notify_parent;
    .kill_agent(Me).

+!notify_parent : parent_plot(Parent) <-
    .my_name(Me);
    .send(Parent, achieve, child_ended(epicadventure, Me)).
+!notify_parent <- true.

@start_subplot_atomic[atomic]
+!start_subplot(SubplotStr, SubplotAtom, MappingsData) <-
    !build_bindings(MappingsData, Bindings);
    // uses current time to generate new distinct sub-plot agent id
    .time(HH, MM, SS, MS);
    .my_name(Me);
    .concat(SubplotStr, "_", Me, "_", MS, ChildId);
    .concat("director_", SubplotStr, ".asl", SourceFile);
    .print("[EpicAdventure] Spawning subplot '", SubplotStr, "' as agent ", ChildId, " with bindings ", Bindings);
    .create_agent(ChildId, SourceFile);
    .send(ChildId, achieve, start_plot(Bindings));
    .send(ChildId, tell, parent_plot(Me));
    +child_plot(ChildId, SubplotAtom, MappingsData).

// Recursive helper to build role agent bindings from mappings
+!build_bindings([], []).
+!build_bindings([map(Target, Source) | RestMappings], [map(Target, Agents) | RestBindings]) <-
    .findall(A, role_agent(Source, A), Agents);
    !build_bindings(RestMappings, RestBindings).

// ============================================
// == Role-Agent Registry ==
// ============================================
// Populated at plot startup via !start_plot.
@dir__EpicAdventure__start_plot__0
+!start_plot(Bindings) <-
    for ( .member(map(Role, Agents), Bindings) ) {
        for ( .member(Agent, Agents) ) {
            +role_agent(Role, Agent);
        }
    };
    !boot.

@dir__EpicAdventure__send_to_role__0
+!send_to_role(Role, Performative, Content) <-
    .findall(A, role_agent(Role, A), Agents);
    .send(Agents, Performative, Content).

// Handle agent death (broadcast by the environment) to avoid stalling
@dir__EpicAdventure__agent_died__0[atomic]
+agent_died(DeadAgent) : role_agent(Role, DeadAgent) <-
    .print("[EpicAdventure] Agent ", DeadAgent, " playing role '", Role, "' has died! Cleaning registry...");
    -role_agent(Role, DeadAgent).

