// ============================================
// == Playbook: Worker ==
// ============================================
// Generated by the Regia v0.2 compiler
// Plans are gated by playbook_active(worker, _).
// Included by role templates that use this playbook.

@pb__Worker__morning_comes__0[priority(5)]
+morning_comes : playbook_active(worker, _) <-
    wake_up;
    +has_coffee.

@pb__Worker__tired__0[priority(5), temper([diligence(0.8)]), effects([stress(-0.5)])]
+tired : playbook_active(worker, _) & has_coffee <-
    .print("Taking a break...");
    -has_coffee.

@pb__Worker__tired__1[priority(5), temper([diligence(0.8)]), effects([stress(-0.5)])]
+tired : playbook_active(worker, _) & not (has_coffee) <-
    .print("Taking a break...");
    .print("I need coffee!").

@pb__Worker__emergency_alarm__0
+emergency_alarm : playbook_active(worker, _) & is_raining <-
    .print("Alarm heard!");
    .send(boss, tell, "Staying inside!").

@pb__Worker__emergency_alarm__1
+emergency_alarm : playbook_active(worker, _) & not (is_raining) <-
    .print("Alarm heard!");
    .broadcast(tell, "Evacuating!");
    !go_home;
    !signal_directors(worker, safe).

