// ============================================
// == Playbook: NobleSocializing ==
// ============================================
// Generated by the Regia v0.2 compiler
// Plans are gated by playbook_active(noblesocializing, _).
// Included by role templates that use this playbook.
//
// desc: Reactive behaviour for guests mingling and eating at the banquet.


@pb__NobleSocializing__insult_heard__0[priority(5), temper([sympathy(-0.5)]), effects([aggressiveness(0.2)])]
+insult_heard : playbook_active(noblesocializing, _) & not (is_drunk) & hates(host) <-
    complain;
    !signal_directors(noblesocializing, insult_thrown).

@pb__NobleSocializing__insult_heard__1[priority(5), temper([sympathy(-0.5)]), effects([aggressiveness(0.2)])]
+insult_heard : playbook_active(noblesocializing, _) & not (not (is_drunk) & hates(host)) <-
    toast(host).

@pb__NobleSocializing__digestion_check__0
+digestion_check : playbook_active(noblesocializing, _) & is_hungry <-
    eat_food;
    -is_hungry;
    .print("A guest finishes their meal.").

@pb__NobleSocializing__food_served__0
+food_served : playbook_active(noblesocializing, _) & (is_hungry | is_drunk) & not (hates(host)) <-
    .print("A guest notices food arriving.");
    eat_food.

@pb__NobleSocializing__food_served__1
+food_served : playbook_active(noblesocializing, _) & not ((is_hungry | is_drunk) & not (hates(host))) <-
    .print("A guest notices food arriving.");
    complain.

