// ============================================
// == Playbook: HeroPlaybook ==
// ============================================
// Generated by the Regia v0.2 compiler
// Plans are gated by playbook_active(heroplaybook, _).
// Included by role templates that use this playbook.

@pb__HeroPlaybook__quest_completed__0[priority(5)]
+quest_completed : playbook_active(heroplaybook, _) <-
    celebrate(achievement_name).

