// ============================================
// == Role: Hero in Plot: EpicAdventure ==
// ============================================
// Generated by the Regia v0.2 compiler

// ============================================
// == Included Playbooks ==
// ============================================
{ include("playbook_heroplaybook.asl") }

// ============================================
// == Playbook Management ==
// ============================================
// When the Director assigns a playbook, add the
// playbook_active belief to enable its gated plans.
+!add_playbook(Name)[source(Sender)] <-
    .print("[Hero] Added playbook ", Name, " from ", Sender);
    +playbook_active(Name, Sender).

+!remove_playbook(Name)[source(Sender)] <-
    .print("[Hero] Removed playbook ", Name, " from ", Sender);
    -playbook_active(Name, Sender).

// Cleanup ghost playbooks when the Plot terminates
+!plot_ended(PlotId)[source(PlotId)] <-
    -playbook_active(_, PlotId).

// Signal all active directors for a given playbook
+!signal_directors(PbName, Payload) <-
    .print("[Hero] Signaling directors of ", PbName, " with ", Payload);
    .findall(D, playbook_active(PbName, D), Directors);
    for ( .member(DirectorId, Directors) ) { .send(DirectorId, untell, Payload); .send(DirectorId, tell, Payload) }.

