// Director agent for Plot: ArenaTrial
// Generated by the Regia v0.2 compiler

// == Initial Beliefs ==
plot_name(arenatrial).
current_phase(warmup).

// == Boot Plan ==
// Runs when the Director agent is created.
// Registers plot identity and executes ON ENTER for the initial phase.
@boot__ArenaTrial[atomic]
+!boot <-
    .my_name(Me);
    +plot_id(Me);
    .print("[ArenaTrial] Booting up director agent ", Me, " in phase 'warmup'...");
    !on_enter(warmup).

// == Director WHEN Plans ==
@dir__ArenaTrial__quest_started__0
+quest_started : current_phase(warmup) <-
    !switch_phase(combat).

@dir__ArenaTrial__victory_achieved__0
+victory_achieved : current_phase(combat) <-
    sound_horn;
    !switch_phase(done).

@dir__ArenaTrial__defeat_suffered__0
+defeat_suffered : current_phase(combat) <-
    !switch_phase(done).

@dir__ArenaTrial__cleanup_done__0
+cleanup_done : current_phase(done) <-
    !end_plot.

@dir__ArenaTrial__parent_ended__0
+parent_ended : true <-
    close_gate;
    !end_plot.


// == Phase Transition Infrastructure ==
@switch_phase_atomic[atomic]
+!switch_phase(Target) : current_phase(Current) <-
    .print("[ArenaTrial] Transitioning from phase '", Current, "' to '", Target, "'...");
    !on_exit(Current);
    -current_phase(Current);
    +current_phase(Target);
    !on_enter(Target).

+!on_exit(warmup) <-
    open_gate.
+!on_enter(warmup) <-
    !send_to_role(fighter, tell, add_playbook(TrialFighter));
    prepare_arena.
+!on_enter(combat) <-
    play_fanfare.
+!on_enter(done) <-
    !send_to_role(fighter, tell, remove_playbook(TrialFighter));
    close_gate.
+!on_exit(_) <- true.
+!on_enter(_) <- true.

// == Plot Lifecycle Infrastructure ==
@end_plot_atomic[atomic]
+!end_plot : current_phase(Current) <-
    .print("[ArenaTrial] Ending plot. Running exit hooks and broadcasting termination...");
    !on_exit(Current);
    .findall(C, child_plot(C, _, _), Children);
    for ( .member(Child, Children) ) { .send(Child, tell, parent_ended) };
    .findall(A, role_agent(_, A), Roles);
    for ( .member(RoleAgent, Roles) ) { .send(RoleAgent, tell, plot_ended(Me)) };
    if ( parent_plot(Parent) ) { .send(Parent, tell, child_ended(arenatrial, Me)) };
    .kill_agent(Me).

@start_subplot_atomic[atomic]
+!start_subplot(SubplotStr, SubplotAtom, Bindings, MappingsData) <-
    .time(HH, MM, SS, MS);
    .concat(SubplotStr, "_", plot_id(Me), "_", MS, ChildId);
    .concat("director_", SubplotStr, ".asl", SourceFile);
    .print("[ArenaTrial] Spawning subplot '", SubplotStr, "' as agent ", ChildId, " with bindings ", Bindings);
    .create_agent(ChildId, SourceFile);
    .send(ChildId, achieve, start_plot(Bindings));
    .send(ChildId, tell, parent_plot(Me));
    +child_plot(ChildId, SubplotAtom, MappingsData).

// == Role-Agent Registry ==
// Populated at plot startup via !start_plot.
@dir__ArenaTrial__start_plot__0
+!start_plot(Bindings) <-
    for ( .member(role_agent(Role, Agent), Bindings) ) {
        +role_agent(Role, Agent);
    }.

@dir__ArenaTrial__send_to_role__0
+!send_to_role(Role, Performative, Content) <-
    .findall(A, role_agent(Role, A), Agents);
    .send(Agents, Performative, Content).

