// Generated by RegiaScript compiler
// Source : test_v2_grammar.rgs
// Agent  : Guard
// Date   : 2026-06-01 12:11:17

// == Plans =================================================
+idle : true <- patrol.
