// Role: Hero in Plot: GrandTest
// Generated by the Regia v0.2 compiler

// == Included Playbooks ==
{ include("playbook_pbcombat.asl") }
{ include("playbook_pbexplore.asl") }

// == Playbook Management ==
// When the Director assigns a playbook, add the
// playbook_active belief to enable its gated plans.
+add_playbook(Name) <-
    +playbook_active(Name).

+remove_playbook(Name) <-
    -playbook_active(Name).

// == Director Commands ==
@role__GrandTest__Hero__speak
+!speak(greetings, "Hello world") <-
    speak(greetings, "Hello world").

@role__GrandTest__Hero__walk
+!walk(away) <-
    walk(away).

