// ============================================
// Director agent for Plot: EpicBattle
// ============================================
// Generated by the Regia v0.2 compiler

// ============================================
// == Initial Beliefs ==
// ============================================
plot_name(epicbattle).
current_phase(peace).

// ============================================
// == Boot Plan ==
// ============================================
// Runs when the Director agent is created.
// Registers plot identity and executes ON ENTER for the initial phase.
@boot__EpicBattle[atomic]
+!boot <-
    .my_name(Me);
    +plot_id(Me);
    .print("[EpicBattle] Booting up director agent ", Me, " in phase 'peace'...");
    !on_enter(peace).

// == Director WHEN Plans ==
@dir__EpicBattle__battle_starts__0
+battle_starts : current_phase(peace) <-
    !switch_phase(war).

@dir__EpicBattle__battle_ends__0
+battle_ends : current_phase(war) <-
    .print("The war is over.");
    !send_to_role(villain, tell, remove_playbook(attacker));
    !end_plot.


// ============================================
// == Phase Transition Infrastructure ==
// ============================================
@switch_phase_atomic[atomic]
+!switch_phase(Target) : current_phase(Current) <-
    .print("[EpicBattle] Transitioning from phase '", Current, "' to '", Target, "'...");
    !on_exit(Current);
    -current_phase(Current);
    +current_phase(Target);
    !on_enter(Target).

+!on_enter(peace) <-
    .print("Peace in the kingdom.");
    !send_to_role(hero, tell, add_playbook(defender)).
+!on_enter(war) <-
    .print("The war has begun!");
    !send_to_role(villain, tell, add_playbook(attacker));
    !send_to_role(hero, achieve, patrol);
    !send_to_role(villain, achieve, attack).
+!on_exit(_) <- true.
+!on_enter(_) <- true.

// ============================================
// == Plot Lifecycle Infrastructure ==
// ============================================
// Handle termination signal from parent plot
+parent_ended[source(Parent)] : parent_plot(Parent) <-
    .print("[EpicBattle] Parent plot ", Parent, " ended. Terminating this subplot...");
    -parent_plot(Parent);
    !end_plot.

@end_plot_atomic[atomic]
+!end_plot : current_phase(Current) <-
    .my_name(Me);
    .print("[EpicBattle] Ending plot. Running exit hooks and broadcasting termination...");
    !on_exit(Current);
    .findall(C, child_plot(C, _, _), Children);
    for ( .member(Child, Children) ) { .send(Child, tell, parent_ended) };
    .findall(A, role_agent(_, A), Roles);
    for ( .member(RoleAgent, Roles) ) { .send(RoleAgent, tell, plot_ended(Me)) };
    !notify_parent;
    .kill_agent(Me).

+!notify_parent : parent_plot(Parent) <-
    .my_name(Me);
    .send(Parent, tell, child_ended(epicbattle, Me)).
+!notify_parent <- true.

@start_subplot_atomic[atomic]
+!start_subplot(SubplotStr, SubplotAtom, MappingsData) <-
    !build_bindings(MappingsData, Bindings);
    // uses current time to generate new distinct sub-plot agent id
    .time(HH, MM, SS, MS);
    .my_name(Me);
    .concat(SubplotStr, "_", Me, "_", MS, ChildId);
    .concat("director_", SubplotStr, ".asl", SourceFile);
    .print("[EpicBattle] Spawning subplot '", SubplotStr, "' as agent ", ChildId, " with bindings ", Bindings);
    .create_agent(ChildId, SourceFile);
    .send(ChildId, achieve, start_plot(Bindings));
    .send(ChildId, tell, parent_plot(Me));
    +child_plot(ChildId, SubplotAtom, MappingsData).

// Recursive helper to build role agent bindings from mappings
+!build_bindings([], []).
+!build_bindings([map(Target, Source) | RestMappings], [map(Target, Agents) | RestBindings]) <-
    .findall(A, role_agent(Source, A), Agents);
    !build_bindings(RestMappings, RestBindings).

// ============================================
// == Role-Agent Registry ==
// ============================================
// Populated at plot startup via !start_plot.
@dir__EpicBattle__start_plot__0
+!start_plot(Bindings) <-
    for ( .member(map(Role, Agents), Bindings) ) {
        for ( .member(Agent, Agents) ) {
            +role_agent(Role, Agent);
        }
    };
    !boot.

@dir__EpicBattle__send_to_role__0
+!send_to_role(Role, Performative, Content) <-
    .findall(A, role_agent(Role, A), Agents);
    .send(Agents, Performative, Content).

// Handle agent death (broadcast by the environment) to avoid stalling
@dir__EpicBattle__agent_died__0[atomic]
+agent_died(DeadAgent) : role_agent(Role, DeadAgent) <-
    .print("[EpicBattle] Agent ", DeadAgent, " playing role '", Role, "' has died! Cleaning registry...");
    -role_agent(Role, DeadAgent).

