// ============================================
// == Playbook: Attacker ==
// ============================================
// Generated by the Regia v0.2 compiler
// Plans are gated by playbook_active(attacker, _).
// Included by role templates that use this playbook.

@pb__Attacker__battle_starts__0
+battle_starts : playbook_active(attacker, _) <-
    attack.

