"""
CLI entry point for the Regia compiler.

Uses Click for argument parsing and provides two subcommands:

Usage::

    regia compile source.rgs                    # print to stdout
    regia compile source.rgs -o output_dir/     # write .asl files
    regia check source.rgs                      # validate only, no output
"""

import sys
from pathlib  import Path
from datetime import datetime
from typing   import Optional

import click

from regia.compiler import compile_file
from regia.errors   import Severity


# == Helpers ===================================================================

def _build_asl_header(source_name: str, agent_name: str) -> str:
    """Build the standard header for generated .asl files.

    Args:
        source_name: The basename of the source .rgs file.
        agent_name:  The name of the agent this file is generated for.

    Returns:
        A multi-line string header with source, agent, and timestamp.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return "\n".join([
        f"// Generated by Regia compiler v0.2",
        f"// Source : {source_name}",
        f"// Agent  : {agent_name}",
        f"// Date   : {timestamp}",
        "",
    ])


def _print_diagnostics(result: "CompileResult") -> None:
    """Print all diagnostics from a compile result with coloured labels.

    Args:
        result: The CompileResult whose messages should be printed.
    """
    if result.messages:
        click.echo("")
    for msg in sorted(result.messages, key=lambda m: m.line):
        if msg.severity == Severity.ERROR:
            label = click.style("ERROR", fg="red", bold=True)
        else:
            label = click.style("WARNING", fg="yellow", bold=True)
        click.echo(f"  {label}  line {msg.line}, col {msg.column}: {msg.message}")
        if msg.hint:
            click.echo(f"         Hint: {msg.hint}")


# == CLI commands ==============================================================

@click.group()
def main() -> None:
    """Regia: DSL for Agent Behaviour and Game Flow."""


@main.command()
@click.argument("source", type=click.Path(exists=True, path_type=Path))
@click.option("-o", "--output", type=click.Path(path_type=Path), default=None,
              help="Output directory for .asl files.")
def compile(source: Path, output: Optional[Path]) -> None:
    """Compile a .rgs source file into AgentSpeak .asl files.

    Args:
        source: Path to the Regia source file.
        output: Optional output directory for .asl files.
    """
    result = compile_file(source)
    _print_diagnostics(result)

    e, w = result.error_count, result.warning_count

    if not result.success:
        click.echo(f"\nCompilation failed: {e} error(s), {w} warning(s).")
        sys.exit(1)

    click.echo(f"\nCompilation successful: {e} error(s), {w} warning(s).")

    # Write outputs
    for agent_name, agentspeak in result.outputs.items():
        header  = _build_asl_header(source.name, agent_name)
        content = header + agentspeak + "\n"

        if output:
            output.mkdir(parents=True, exist_ok=True)
            out_path = output / f"{agent_name}.asl"
            out_path.write_text(content, encoding="utf-8")
            click.echo(f"  [OK] {out_path}")
        else:
            click.echo(f"\n{'=' * 60}")
            click.echo(f"  AGENT: {agent_name}")
            click.echo(f"{'=' * 60}\n")
            click.echo(content)


@main.command()
@click.argument("source", type=click.Path(exists=True, path_type=Path))
def check(source: Path) -> None:
    """Validate a .rgs source file without emitting output.

    Args:
        source: Path to the Regia source file to validate.
    """
    result = compile_file(source)
    _print_diagnostics(result)

    e, w = result.error_count, result.warning_count

    if result.success:
        click.echo(click.style(f"\n+ Valid: {w} warning(s).", fg="green"))
    else:
        click.echo(f"\nx Invalid: {e} error(s), {w} warning(s).")
        sys.exit(1)
