// Director agent for Plot: Concert
// Generated by the Regia v0.2 compiler

// == Initial Beliefs ==
current_phase(backstage).

// == Boot Plan ==
// Runs when the Director agent is created.
// Executes the ON ENTER hook for the initial phase.
@boot__Concert[atomic]
+!boot <- 
    !send_to_role(singer, tell, add_playbook(SingerInBackstage));
    add_waiting_for_concert.

// == Phase Transitions ==
// TRANSITION: backstage -> performing on time_to_start
@tr__Concert__backstage_to_performing__time_to_start[atomic]
+time_to_start : current_phase(backstage) <-
    !send_to_role(singer, tell, remove_playbook(SingerInBackstage));
    !send_to_role(singer, achieve, flee);
    announce_concert;
    -current_phase(backstage);
    +current_phase(performing);
    !send_to_role(singer, tell, add_playbook(SingerOnStage));
    start_music.

// TRANSITION: performing -> aftermath on song_ends
@tr__Concert__performing_to_aftermath__song_ends[atomic]
+song_ends : current_phase(performing) & audience_satisfied <-
    !send_to_role(singer, tell, remove_playbook(SingerOnStage));
    -current_phase(performing);
    +current_phase(aftermath).


// == Director WHEN Plans ==
@dir__Concert__emergency__0[priority(9)]
+emergency : true <-
    trigger_alarm;
    !send_to_role(singer, achieve, acknowledge);
    !send_to_role(audiencemember, achieve, acknowledge).


// == Role-Agent Registry ==
// Populated at plot startup via !start_plot.
@dir__Concert__start_plot__0
+!start_plot(Bindings) <-
    for ( .member(role_agent(Role, Agent), Bindings) ) {
        +role_agent(Role, Agent);
    }.

@dir__Concert__send_to_role__0
+!send_to_role(Role, Performative, Content) <-
    .findall(A, role_agent(Role, A), Agents);
    .send(Agents, Performative, Content).

