// Playbook: SingerOnStage
// Generated by the Regia v0.2 compiler
//
// Plans are gated by playbook_active(SingerOnStage).
// Included by role templates that use this playbook.

@pb__SingerOnStage__audience_cheers__0
+audience_cheers : playbook_active(SingerOnStage) <-
    bow;
    !perform_song.

