// Playbook: SingerInBackstage
// Generated by the Regia v0.2 compiler
//
// Plans are gated by playbook_active(SingerInBackstage).
// Included by role templates that use this playbook.

@pb__SingerInBackstage__fan_greets__0
+fan_greets : playbook_active(SingerInBackstage) & happy <-
    greet_back.

@pb__SingerInBackstage__fan_greets__1
+fan_greets : playbook_active(SingerInBackstage) & angry <-
    curse.

@pb__SingerInBackstage__fan_greets__2
+fan_greets : playbook_active(SingerInBackstage) & not (happy) & not (angry) <-
    ignore.

@pb__SingerInBackstage__player_asks_about_quest__0[priority(7)]
+player_asks_about_quest : playbook_active(SingerInBackstage) <-
    .send(player, tell, busy_message).

@pb__SingerInBackstage__emergency__0
+emergency : playbook_active(SingerInBackstage) <-
    flee;
    .send(director, tell, emergency).

