// Role: Singer in Plot: Concert
// Generated by the Regia v0.2 compiler

// == Included Playbooks ==
{ include("playbook_singerinbackstage.asl") }
{ include("playbook_singeronstage.asl") }

// == Playbook Management ==
// When the Director assigns a playbook, add the
// playbook_active belief to enable its gated plans.
+add_playbook(Name) <-
    +playbook_active(Name).

+remove_playbook(Name) <-
    -playbook_active(Name).

// == Director Commands ==
@role__Concert__Singer__acknowledge
+!acknowledge <-
    acknowledge.

@role__Concert__Singer__flee
+!flee <-
    flee.

