// Role template: Singer
// Generated by the Regia v0.2 compiler

// == Playbook Management ==
// When the Director assigns a playbook, add the
// playbook_active belief to enable its gated plans.
+add_playbook(Name) <-
    +playbook_active(Name).

+remove_playbook(Name) <-
    -playbook_active(Name).

// == Playbook: SingerInBackstage (static-gated) ==
+fan_greets : playbook_active(SingerInBackstage) & happy <-
    greet_back.

+fan_greets : playbook_active(SingerInBackstage) & angry <-
    curse.

+fan_greets : playbook_active(SingerInBackstage) & not (happy) & not (angry) <-
    ignore.

@priority_7
+player_asks_about_quest : playbook_active(SingerInBackstage) <-
    .send(player, tell, busy_message).

+emergency : playbook_active(SingerInBackstage) <-
    flee;
    .send(director, tell, emergency).


// == Playbook: SingerOnStage (static-gated) ==
+audience_cheers : playbook_active(SingerOnStage) <-
    bow;
    !perform_song.


