// Director agent for Plot: SimplePlot
// Generated by the Regia v0.2 compiler

// == Initial Beliefs ==
current_phase(first).

// == Boot Plan ==
// Runs when the Director agent is created.
// Executes the ON ENTER hook for the initial phase.
@boot__SimplePlot
+!boot <- 
    .print("Entering first phase");
    !send_to_role(rolea, tell, add_playbook(PbOne));
    !send_to_role(rolea, achieve, print("RoleA is active in first phase")).

// == Phase Transitions ==
// TRANSITION: first -> second on next_phase
@tr__SimplePlot__first_to_second__next_phase
+next_phase : current_phase(first) <-
    !send_to_role(rolea, tell, remove_playbook(PbOne));
    -current_phase(first);
    +current_phase(second);
    .print("Entering second phase");
    !send_to_role(roleb, tell, add_playbook(PbTwo));
    !send_to_role(roleb, achieve, print("RoleB is active in second phase")).


// == Role-Agent Registry ==
// Populated at plot startup via !start_plot.
@dir__SimplePlot__start_plot__0
+!start_plot(Bindings) <-
    for ( .member(role_agent(Role, Agent), Bindings) ) {
        +role_agent(Role, Agent);
    }.

@dir__SimplePlot__send_to_role__0
+!send_to_role(Role, Performative, Content) <-
    .findall(A, role_agent(Role, A), Agents);
    .send(Agents, Performative, Content).

