// Playbook: PbTwo
// Generated by the Regia v0.2 compiler
//
// Plans are gated by playbook_active(PbTwo).
// Included by role templates that use this playbook.

@pb__PbTwo__end_event__0
+end_event : playbook_active(PbTwo) <-
    .print("PbTwo ended").

