// Role: RoleB in Plot: SimplePlot
// Generated by the Regia v0.2 compiler

// == Included Playbooks ==
{ include("playbook_pbtwo.asl") }

// == Playbook Management ==
// When the Director assigns a playbook, add the
// playbook_active belief to enable its gated plans.
+add_playbook(Name) <-
    +playbook_active(Name).

+remove_playbook(Name) <-
    -playbook_active(Name).

// == Director Commands ==
@role__SimplePlot__RoleB__print
+!print("RoleB is active in second phase") <-
    .print("RoleB is active in second phase").

