// Director agent for Plot: GrandQuest
// Generated by the Regia v0.2 compiler

// == Initial Beliefs ==
plot_name(GrandQuest).
current_phase(intro).

// == Boot Plan ==
// Runs when the Director agent is created.
// Registers plot identity and executes ON ENTER for the initial phase.
@boot__GrandQuest[atomic]
+!boot <-
    .my_name(Me);
    +plot_id(Me)
;    // --- START SUBPLOT ArenaTrial ---;
    .concat("arenatrial_", plot_id(Me), ChildId);
    .create_agent(ChildId, "director_arenatrial.asl");
    .findall(A, role_agent(hero, A), Agents_0);
    !build_bindings([map(fighter, Agents_0)], Bindings);
    .send(ChildId, achieve, start_plot(Bindings));
    .send(ChildId, tell, parent_plot(Me));
    +child_plot(ChildId, ArenaTrial, [map(fighter, hero)]);
    // --- START SUBPLOT ArenaTrial ---;
    .concat("arenatrial_", plot_id(Me), ChildId);
    .create_agent(ChildId, "director_arenatrial.asl");
    .findall(A, role_agent(champion, A), Agents_0);
    !build_bindings([map(fighter, Agents_0)], Bindings);
    .send(ChildId, achieve, start_plot(Bindings));
    .send(ChildId, tell, parent_plot(Me));
    +child_plot(ChildId, ArenaTrial, [map(fighter, champion)]);
    sound_horn.

// == Phase Transitions ==
// TRANSITION: intro -> trials on quest_started
@tr__GrandQuest__intro_to_trials__quest_started[atomic]
+quest_started : current_phase(intro) <-
    -current_phase(intro);
    +current_phase(trials);
    open_gate.


// == Director WHEN Plans ==
@dir__GrandQuest__child_ended__0
+child_ended : current_phase(trials) & all_trials_passed <-
    -current_phase(trials);
    +current_phase(finale);
    award_trophy.

@dir__GrandQuest__quest_complete__0
+quest_complete : current_phase(trials) & all_trials_passed <-
    -current_phase(trials);
    +current_phase(finale);
    award_trophy.

@dir__GrandQuest__cleanup_done__0
+cleanup_done : current_phase(finale) <-
    pack_up;
    // --- END PLOT ---;
    .findall(C, child_plot(C, _, _), Children);
    for ( .member(Child, Children) ) { .send(Child, tell, parent_ended) };
    if ( parent_plot(Parent) ) { .send(Parent, tell, child_ended(GrandQuest, Me)) };
    .kill_agent(self).

@dir__GrandQuest__parent_ended__0
+parent_ended : true <-
    close_gate;
    // --- END PLOT ---;
    .findall(C, child_plot(C, _, _), Children);
    for ( .member(Child, Children) ) { .send(Child, tell, parent_ended) };
    if ( parent_plot(Parent) ) { .send(Parent, tell, child_ended(GrandQuest, Me)) };
    .kill_agent(self).


// == Role-Agent Registry ==
// Populated at plot startup via !start_plot.
@dir__GrandQuest__start_plot__0
+!start_plot(Bindings) <-
    for ( .member(role_agent(Role, Agent), Bindings) ) {
        +role_agent(Role, Agent);
    }.

@dir__GrandQuest__send_to_role__0
+!send_to_role(Role, Performative, Content) <-
    .findall(A, role_agent(Role, A), Agents);
    .send(Agents, Performative, Content).

