// Director agent for Plot: ArenaTrial
// Generated by the Regia v0.2 compiler

// == Initial Beliefs ==
plot_name(ArenaTrial).
current_phase(warmup).

// == Boot Plan ==
// Runs when the Director agent is created.
// Registers plot identity and executes ON ENTER for the initial phase.
@boot__ArenaTrial[atomic]
+!boot <-
    .my_name(Me);
    +plot_id(Me)
;    !send_to_role(fighter, tell, add_playbook(TrialFighter));
    prepare_arena.

// == Phase Transitions ==
// TRANSITION: warmup -> combat on quest_started
@tr__ArenaTrial__warmup_to_combat__quest_started[atomic]
+quest_started : current_phase(warmup) <-
    open_gate;
    -current_phase(warmup);
    +current_phase(combat);
    play_fanfare.


// == Director WHEN Plans ==
@dir__ArenaTrial__victory_achieved__0
+victory_achieved : current_phase(combat) <-
    sound_horn;
    -current_phase(combat);
    +current_phase(done);
    !send_to_role(fighter, tell, remove_playbook(TrialFighter));
    close_gate.

@dir__ArenaTrial__defeat_suffered__0
+defeat_suffered : current_phase(combat) <-
    -current_phase(combat);
    +current_phase(done);
    !send_to_role(fighter, tell, remove_playbook(TrialFighter));
    close_gate.

@dir__ArenaTrial__cleanup_done__0
+cleanup_done : current_phase(done) <-
    // --- END PLOT ---;
    .findall(C, child_plot(C, _, _), Children);
    for ( .member(Child, Children) ) { .send(Child, tell, parent_ended) };
    if ( parent_plot(Parent) ) { .send(Parent, tell, child_ended(ArenaTrial, Me)) };
    .kill_agent(self).

@dir__ArenaTrial__parent_ended__0
+parent_ended : true <-
    close_gate;
    // --- END PLOT ---;
    .findall(C, child_plot(C, _, _), Children);
    for ( .member(Child, Children) ) { .send(Child, tell, parent_ended) };
    if ( parent_plot(Parent) ) { .send(Parent, tell, child_ended(ArenaTrial, Me)) };
    .kill_agent(self).


// == Role-Agent Registry ==
// Populated at plot startup via !start_plot.
@dir__ArenaTrial__start_plot__0
+!start_plot(Bindings) <-
    for ( .member(role_agent(Role, Agent), Bindings) ) {
        +role_agent(Role, Agent);
    }.

@dir__ArenaTrial__send_to_role__0
+!send_to_role(Role, Performative, Content) <-
    .findall(A, role_agent(Role, A), Agents);
    .send(Agents, Performative, Content).

