// Playbook: TrialFighter
// Generated by the Regia v0.2 compiler
//
// Plans are gated by playbook_active(TrialFighter).
// Included by role templates that use this playbook.

@pb__TrialFighter__victory_achieved__0
+victory_achieved : playbook_active(TrialFighter) <-
    +all_trials_passed;
    .send(director, tell, quest_complete).

@pb__TrialFighter__defeat_suffered__0
+defeat_suffered : playbook_active(TrialFighter) <-
    -all_trials_passed;
    .send(director, tell, quest_complete).

