// Role: Fighter in Plot: ArenaTrial
// Generated by the Regia v0.2 compiler

// == Included Playbooks ==
{ include("playbook_trialfighter.asl") }

// == Playbook Management ==
// When the Director assigns a playbook, add the
// playbook_active belief to enable its gated plans.
+add_playbook(Name) <-
    +playbook_active(Name).

+remove_playbook(Name) <-
    -playbook_active(Name).

