// Generated by RegiaScript compiler
// Source : new_features_test.rgs
// Agent  : Player
// Date   : 2026-06-17 11:11:40

// == Infrastructure plans ===================================
@atomic
+!enter_phase(Story, Phase)
    <- -current_phase(Story, _); +current_phase(Story, Phase).

@atomic
+!activate_story(Name, Priority)
    <- +story(Name, Priority).

@atomic
+!deactivate_story(Name)
    <- -story(Name, _).

// == Plans =================================================
+bored : true <- explore.
