// Generated by RegiaScript compiler
// Source : test_emitter.txt
// Agent  : test_emitter
// Date   : 2026-05-25 11:20:50

// ── Plans ────────────────────────────────────────────────
+spotted[source(percept)] : story(alert, 2) & is_armed & ~is_tired <- run; hide.
+spotted[source(percept)] : story(alert, 2) & (is_tired | door_open) & ~is_armed <- hide.
+lost[source(percept)] : story(alert, 2) <- -is_armed; +is_tired.
+spotted[source(percept)] : story(patrol, 1) & (is_armed | is_tired) <- hide.
+order[source(director)] : story(patrol, 1) & ~(is_tired & is_armed) <- scan.
+spotted[source(percept)] : ~is_tired <- run.
+order[source(director)] : true <- dance.
