## Player: Handles user-driven movement, animation direction
class_name Player
extends CharacterBody2D

# ==============================================================================
# PHYSICS CONFIGURATION
# ==============================================================================
## Base movement speed.
@export var DEFAULT_SPEED: float = 50.0

## Movement multiplier used to derive runtime speed.
var speed_factor: float = 1.0:
	set(new_factor):
		speed_factor = new_factor
		speed = DEFAULT_SPEED * speed_factor

## Runtime speed value.
@onready var speed: float = DEFAULT_SPEED * speed_factor

## Base weight used for knockback interactions.
@export var DEFAULT_WEIGHT: float = 100

## Weight multiplier used to derive runtime weight.
var weight_factor: float = 1.0:
	set(new_factor):
		weight_factor = new_factor
		weight = DEFAULT_WEIGHT * weight_factor

## Runtime weight value.
@onready var weight: float = DEFAULT_WEIGHT * weight_factor

## Surface resistance multiplier.
var resistance: float = 1.0:
	set(new_resistance):
		resistance = clampf(new_resistance, 0, INF)

## Sliding factor used during velocity interpolation.
var friction: float = 100:
	get():
		return friction * speed / 100

# Used for determining movement direction sectors.
const SECTOR_ANGLE := TAU / 8

## Last non-zero movement direction from input.
var last_dpad_direction: Vector2 = Vector2.DOWN

# ==============================================================================
# STATE & NODES
# ==============================================================================

## Lock to prevent movement during dialogue.
var can_move: bool = true

@onready var interact_ray: RayCast2D = $Interactor
const INTERACT_DISTANCE: float = 400.0

# ==============================================================================
# LIFECYCLE
# ==============================================================================

func _ready() -> void:
	# Make the ray point "Right" in local space so rotation angle perfectly matches dpad_direction.angle()
	interact_ray.target_position = Vector2.RIGHT * INTERACT_DISTANCE

# ==============================================================================
# PHYSICS & INTERACTION LOOP
# ==============================================================================

func _physics_process(_delta: float) -> void:
	if not can_move:
		velocity = Vector2.ZERO
		move_and_slide()
		return
	
	compute_animations()
	compute_movement()
	move_and_slide()
	
	if Input.is_action_just_pressed("ui_accept"):
		attempt_interaction()

## Attempts to interact with objects in the world using the RayCast2D.
## If a collision is found and the object has an `interact()` method, it calls it.
func attempt_interaction() -> void:
	interact_ray.force_raycast_update()
	if interact_ray.is_colliding():
		var target = interact_ray.get_collider()
		print("Raycast hit: ", target.name if target else "Unknown")
		if target and target.has_method("interact"):
			target.interact(self)
		else:
			print("Target does not have an interact() method.")
	else:
		print("Raycast did not hit anything.")

# ==============================================================================
# GAMEPLAY HELPERS
# ==============================================================================

## Computes the appropriate animation string and flips the sprite based on input direction.
##
## @param dpad_direction The current movement vector from input.
func compute_animations(dpad_direction: Vector2 = Vector2.ZERO) -> void:
	var _anim_string: String = "idle"
	
	if dpad_direction != Vector2.ZERO:
		var ang = dpad_direction.angle()
		if ang < 0:
			ang += TAU
	
		match int(floor((ang + SECTOR_ANGLE * 0.5) / SECTOR_ANGLE)):
			0, 1, 2: # Right / East
				_anim_string = "walk"
				$Sprite.flip_h = false
			3, 4, 5: # Left / West (Mirrored)
				_anim_string = "walk"
				$Sprite.flip_h = true
			6, 7: # Up
				_anim_string = "walk_up"
				$Sprite.flip_h = false

## Computes movement generated by user input.
## Reads input mapping, updates the raycast rotation, and returns the raw velocity.
##
## @return Vector2 The raw velocity based on input and speed.
func compute_input_movement() -> Vector2:
	var dpad_direction = Input.get_vector("left", "right", "up", "down")
	compute_animations(dpad_direction)
	
	if dpad_direction != Vector2.ZERO and dpad_direction != last_dpad_direction:
		last_dpad_direction = dpad_direction.normalized()
		# Rotate the actual node so attached sprites spin correctly
		interact_ray.rotation = last_dpad_direction.angle()
		
	return dpad_direction * speed

## Computes final movement vector after friction/resistance adjustment.
func compute_movement():
	var input_velocity = compute_input_movement()
	var abstract_velocity = input_velocity
	velocity = velocity.move_toward(abstract_velocity / resistance, friction)
