// Playbook: PbOne
// Generated by the Regia v0.2 compiler
//
// Plans are gated by playbook_active(PbOne).
// Included by role templates that use this playbook.

@pb__PbOne__start_event__0
+start_event : playbook_active(PbOne) <-
    .print("PbOne started").

