// Director agent for Plot: Journey
// Generated by the Regia v0.2 compiler

// == Initial Beliefs ==
current_phase(peace).

// == Boot Plan ==
// Runs when the Director agent is created.
// Executes the ON ENTER hook for the initial phase.
@boot__Journey[atomic]
+!boot <- 
    .print("Peace begins");
    !send_to_role(hero, tell, add_playbook(PbExplore));
    !send_to_role(hero, achieve, speak(greetings, "Hello world")).

// == Phase Transitions ==
// TRANSITION: peace -> battle on danger_spotted
@tr__Journey__peace_to_battle__danger_spotted[atomic]
+danger_spotted : current_phase(peace) & not (is_daytime) <-
    !send_to_role(hero, tell, remove_playbook(PbExplore));
    !send_to_role(hero, achieve, walk(away));
    -current_phase(peace);
    +current_phase(battle);
    !send_to_role(hero, tell, add_playbook(PbCombat));
    .print("Battle begins").

// TRANSITION: battle -> peace on safe_again
@tr__Journey__battle_to_peace__safe_again[atomic]
+safe_again : current_phase(battle) <-
    -current_phase(battle);
    +current_phase(peace);
    .print("Peace begins");
    !send_to_role(hero, tell, add_playbook(PbExplore));
    !send_to_role(hero, achieve, speak(greetings, "Hello world")).


// == Director WHEN Plans ==
@dir__Journey__timer_ticked__0[priority(2)]
+timer_ticked : current_phase(peace) <-
    .broadcast(tell, start_scene).

@dir__Journey__start_scene__0
+start_scene : true <-
    .print("Plot is starting!").


// == Role-Agent Registry ==
// Populated at plot startup via !start_plot.
@dir__Journey__start_plot__0
+!start_plot(Bindings) <-
    for ( .member(role_agent(Role, Agent), Bindings) ) {
        +role_agent(Role, Agent);
    }.

@dir__Journey__send_to_role__0
+!send_to_role(Role, Performative, Content) <-
    .findall(A, role_agent(Role, A), Agents);
    .send(Agents, Performative, Content).

