// Playbook: PbExplore
// Generated by the Regia v0.2 compiler
//
// Plans are gated by playbook_active(PbExplore).
// Included by role templates that use this playbook.

@pb__PbExplore__start_scene__0
+start_scene : playbook_active(PbExplore) <-
    .print("Exploration started");
    +has_weapon.

@pb__PbExplore__danger_spotted__0[priority(8)]
+danger_spotted : playbook_active(PbExplore) & has_weapon & not (health_low) <-
    hide;
    speak(threat);
    .send(director, tell, timer_ticked).

@pb__PbExplore__danger_spotted__1[priority(8)]
+danger_spotted : playbook_active(PbExplore) & health_low | not (is_daytime) <-
    hide;
    .print("Too weak to fight");
    .send(director, tell, safe_again).

@pb__PbExplore__danger_spotted__2[priority(8)]
+danger_spotted : playbook_active(PbExplore) & not (has_weapon & not (health_low)) & not (health_low | not (is_daytime)) <-
    hide;
    -has_weapon.

