// ============================================
// == Playbook: Dummy ==
// ============================================
// Generated by the Regia v0.2 compiler
// Plans are gated by playbook_active(dummy, _).
// Included by role templates that use this playbook.

@pb__Dummy__test_event__0
+test_event : playbook_active(dummy, _) <-
    +pizza_eaten;
    -water_drunk.

