import sys
from pathlib  import Path
from datetime import datetime

from src.compiler import compile_file
from src.errors   import Severity


def build_asl(source_path: str, agent_name: str, agentspeak: str) -> str:
    timestamp   = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    source_name = Path(source_path).name
    divider     = "=" * 48

    return "\n".join([
        f"// Generated by RegiaScript compiler",
        f"// Source : {source_name}",
        f"// Agent  : {agent_name}",
        f"// Date   : {timestamp}",
        f"",
        agentspeak,
        "",
    ])


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python main.py <source.rgs> [output_dir/]")
        sys.exit(1)

    source_path = sys.argv[1]
    output_dir  = Path(sys.argv[2]) if len(sys.argv) > 2 else None

    result = compile_file(source_path)

    # Print all messages
    divider = "=" * 60
    for msg in sorted(result.messages, key=lambda m: m.line):
        label = "ERROR" if msg.severity == Severity.ERROR else "WARNING"
        print(f"\n{divider}")
        print(f" {label}  line {msg.line}, column {msg.column}")
        print(f" {msg.message}")
        if msg.hint:
            print(f" Hint: {msg.hint}")
        if msg.source_line:
            print()
            print(f"    {msg.source_line}")
            caret = " " * (4 + msg.column) + "^" * msg.length
            print(caret)
        print(divider)

    e = result.error_count
    w = result.warning_count
    print()
    if not result.success:
        print(f"Compilation failed: {e} error(s), {w} warning(s).")
        sys.exit(1)

    print(f"Compilation successful: {e} error(s), {w} warning(s).")

    # Write output files
    for agent_name, agentspeak in result.outputs.items():
        asl = build_asl(source_path, agent_name, agentspeak)

        if output_dir:
            output_dir.mkdir(parents=True, exist_ok=True)
            # Single-agent mode uses source filename
            if agent_name == "__single__":
                out = output_dir / (Path(source_path).stem + ".asl")
            else:
                out = output_dir / f"{agent_name}.asl"
            out.write_text(asl, encoding="utf-8")
            print(f"[OK] Written to {out}")
        else:
            # Print to stdout
            print(f"\n{'═' * 60}")
            if agent_name == "__single__":
                print(f"  GLOBAL PLANS")
            else:
                print(f"  AGENT: {agent_name}")
            print(f"{'═' * 60}\n")
            print(asl)