// Playbook: PbCombat
// Generated by the Regia v0.2 compiler
//
// Plans are gated by playbook_active(PbCombat).
// Included by role templates that use this playbook.

@pb__PbCombat__timer_ticked__0
+timer_ticked : playbook_active(PbCombat) & has_weapon <-
    speak(attack_cry, "Charge!");
    walk(forward).

